In [8]:
import os, pandas as pd, numpy as np, re, random

s = 'ams'

In [9]:
# dir()

In [60]:
for num in range(-15,-30,-1):
    print(num, end=" ")

-15 -16 -17 -18 -19 -20 -21 -22 -23 -24 -25 -26 -27 -28 -29 

#### String

In [ ]:
s = "Python"
s[0]   # 'P'  → first character
s[-1]  # 'n'  → last character
s[1:4] # 'yth' → slicing: start to end-1
s[:3]  # 'Pyt' → from start
s[3:]  # 'hon' → till end
s[:]   # full copy
s[::2] # 'Pto' → step
s[::-1]# 'nohtyP' → reverse string

'nohtyP'

In [68]:
s = "hello"
s.upper()   # 'HELLO'
s.lower()   # 'hello'
s.title()   # 'Hello World'
s.capitalize() # 'Hello'
s.swapcase() # 'hELLO'


'HELLO'

In [87]:
r = r"C:\new\test"  # backslashes not escaped
print(r)  # C:\new\test


C:\new\test


In [ ]:
s = "  Python  "
s.strip()   # 'Python'  → removes spaces
s.lstrip()  # 'Python  ' → left
s.rstrip()  # '  Python' → right
s.center(20,'*') # '**  Python  **'
s.ljust(10,'-')  # 'Python----'
s.rjust(10,'-')  # '----Python'

'  Python  '

In [77]:
s = "I love Python"
s.find("Python")   # 7 → index
s.rfind("o")       # 8 → last occurrence
s.index("Python")  # 7 → error if not found
s.replace("Python","Java") # 'I love Java'

'I love Java'

In [78]:
s = "Python is fun"
s.split()      # ['Python', 'is', 'fun'] → default by space
s.split('i')   # ['Python ', 's fun']
"-".join(["Python","is","fun"])  # 'Python-is-fun'


'Python-is-fun'

In [79]:
s = "Python"
s.isalpha()   # True → only letters
s.isdigit()   # True → only digits
s.isalnum()   # True → letters + digits
s.islower()   # True
s.isupper()   # True
s.isspace()   # True → only spaces
s.startswith("Py") # True
s.endswith("on")   # True


True

In [80]:
s = "Python Python"
s.count("Python")  # 2
s.count("o")       # 2


2

In [82]:
name = "Alice"
age = 25
print("My name is %s and I am %d" % (name, age))

"My name is {} and I am {}".format(name, age)
"My name is {0} and I am {1}".format(name, age)
"My name is {n} and I am {a}".format(n=name, a=age)


My name is Alice and I am 25


'My name is Alice and I am 25'

In [83]:
# from python 3.6
f"My name is {name} and I am {age}"
f"{2+3}"   # '5'
f"{age:04}" # pad with 0 → '0025'
f"{3.14159:.2f}" # '3.14' → 2 decimal points


'3.14'

In [84]:
s = "Hello\u0020World"  # Unicode code
print(s)  # Hello World
s.encode() # b'Hello World' → bytes
b = b"Python"
b.decode() # 'Python'


Hello World


'Python'

In [85]:
a = "abc"
b = "ABC"
a == b        # False
a.lower() == b.lower()  # True
a > b         # True → lexicographic


True

In [86]:
str(123)     # '123'
int("123")   # 123
float("3.14")# 3.14
list("abc")  # ['a','b','c']


['a', 'b', 'c']

In [102]:
s = "I love Python"
s[-len(s)] # goes from -1 for lasrt to -len(s) first char
s.find('o', 4)

11

In [91]:
s = '123456789'
s[len(s)//2]

'5'

In [93]:
a = 'hi'
b = a.upper()
print(a, b)

hi HI


#### LIST



A list is an ordered, mutable, collection of elements.

Elements can be of any data type (int, str, float, list, etc.).

Lists are defined using square brackets [].


Lists are mutable, tuples are immutable.

Indexing can be negative.

Slicing returns a new list, original is unchanged.

List comprehension is faster than loops.

append() adds one element, extend() adds iterable elements.

copy() is shallow → nested lists can still be linked.

sort() vs sorted() difference: in-place vs new list.

In [106]:
my_list = [1, 2, 3, 4]
mixed_list = [1, "hello", 3.5, [1,2]]
empty_list = []
lst = [10, 20, 30, 40]
print(lst[0])  # 10
print(lst[-1]) # 40 (last element)
lst[1] = 99  # [1,99,3]



10
40


In [104]:
# 3.1 Adding Elements
# append(x) → adds single element at the end
# extend(iterable) → adds all elements of iterable
# insert(index, x) → inserts element at specific index

lst = [1,2,3]
lst.append(4)       # [1,2,3,4]
lst.extend([5,6])   # [1,2,3,4,5,6]
lst.insert(2, 99)   # [1,2,99,3,4,5,6]


In [105]:
# 3.2 Removing Elements
# remove(x) → remove first occurrence of x
# pop([index]) → remove element at index (default last)
# del lst[index] → remove element at index
# clear() → remove all elements

lst = [1,2,3,2,4]
lst.remove(2)   # [1,3,2,4]
lst.pop()       # [1,3,2] (removes last)
del lst[1]      # [1,2]
lst.clear()     # []


In [107]:
# List Queries & Information
# len(lst) → length
# min(lst) / max(lst) → min/max value
# sum(lst) → sum of elements (numbers only)
# count(x) → count occurrences
# index(x, start, end) → find first index
# in / not in → check presence

lst = [1,2,3,2]
print(len(lst))     # 4
print(lst.count(2)) # 2
print(2 in lst)     # True
print(lst.index(3)) # 2


4
2
True
2


In [108]:
# Sorting & Reversing
# sort() → sorts ascending (in-place)
# sort(reverse=True) → descending
# sorted(lst) → returns sorted copy
# reverse() → reverses in-place
# lst[::-1] → reversed copy

lst = [3,1,4,2]
lst.sort()          # [1,2,3,4]
lst.sort(reverse=True)  # [4,3,2,1]
print(sorted(lst))  # returns [1,2,3,4]
lst.reverse()       # reverse in-place


[1, 2, 3, 4]


In [109]:
# Copying Lists
# lst2 = lst → shallow copy (both point to same list)
# lst.copy() → shallow copy (independent)
# copy.deepcopy(lst) → for nested lists (need import copy)

import copy
lst = [[1,2],[3,4]]
lst2 = copy.deepcopy(lst)


In [110]:
l1 = [1, 2, 3, 4]
l2 = l1
l2[0] = 2
l1

[2, 2, 3, 4]

In [111]:
# From string → list: list("hello") → ['h','e','l','l','o']
# From list → string: ''.join(['h','e']) → "he"

In [114]:
# if not lst:
#     print("Empty")
# lst[::-1]
# Copy a list
# lst2 = lst[:]
# Flatten a nested list

nested = [[1,2],[3,4], [1, [2, 3]]]
flat = [i for sub in nested for i in sub]  # [1,2,3,4]
flat

[1, 2, 3, 4, 1, [2, 3]]

#### Dict

A dictionary is an unordered (Python <3.7), mutable collection of key-value pairs.

Keys must be immutable (int, str, tuple), values can be any type (int, str, list, dict, etc.).

Dictionaries are defined using curly braces {}:

Access elements: d[key] or d.get(key, default) → avoids KeyError.

Mutable → keys can’t change, values can be updated.

Add/Update: d[key] = value or d.update({'key': value}).

Delete: del d[key], d.pop(key), d.popitem() (last inserted key).

Copying:

copy() → shallow (nested dicts still linked)

deepcopy() → fully independent copy

Iterating:

d.keys() → keys

d.values() → values

d.items() → key-value pairs

Merge: d1.update(d2) (Python <3.9), d3 = d1 | d2 (Python 3.9+)

Sorting:

By key: dict(sorted(d.items()))

By value: dict(sorted(d.items(), key=lambda x: x[1]))

reverse=True → descending order

Nested dictionaries: Access with d[key1][key2].

Tricks/Useful methods:

setdefault(key, default) → create key if missing

max(d, key=d.get) → max value key

min(d, key=d.get) → min value key

Swap keys/values: {v:k for k,v in d.items()}

Important points:

d.items(), d.keys(), d.values() are views, not lists

Dictionary preserves insertion order from Python 3.7+

In [ ]:
d = {}

# With values
d = {'a': 1, 'b': 2, 'c': 3}
# Using dict() constructor
d = dict(a=1, b=2, c=3)
# From a list of tuples
d = dict([('a', 1), ('b', 2)])
# From keys with same value
d = dict.fromkeys(['x', 'y', 'z'], 0)  # {'x':0, 'y':0, 'z':0}


keys = ['a', 'b', 'c']
values = [1, 2, 3]

# Using zip
d = dict(zip(keys, values))
print(d)  # {'a': 1, 'b': 2, 'c': 3}   #If lists are unequal, zip stops at the shortest list.

{'a': 1, 'b': 2, 'c': 3}


In [ ]:
d = {'a': 1, 'b': 2}

# Access by key
print(d['a'])  # 1

# Access safely using get()
print(d.get('c'))         # None
print(d.get('c', 0))      # 0 (default value if key not present)

d.update({'b': 20, 'd': 4, 'a': 2}) # if new dict have key which is in old dict it will update old
d

1
None
0


{'a': 2, 'b': 20, 'd': 4}

In [122]:
# Deleting Elements
d = {'a': 1, 'b': 2, 'c': 3}

# Delete key
del d['b']        # {'a':1, 'c':3}

# Remove and return value
val = d.pop('c')  # val=3, d={'a':1}

# Remove last inserted item (Python 3.7+)
d.popitem()        # removes last key-value pair

# Clear dictionary
d.clear()          

    d.keys()	Returns all keys (dict_keys object)
    d.values()	Returns all values (dict_values object)
    d.items()	Returns key-value pairs as tuples
    d.get(key, default)	Returns value for key, default if not found
    d.update(other_dict)	Adds or updates key-value pairs
    d.pop(key)	Removes key and returns value
    d.popitem()	Removes and returns last inserted key-value pair
    d.clear()	Clears dictionary
    d.copy()	Returns a shallow copy
    dict.fromkeys(seq, value)	Creates new dict from keys with same value

In [124]:
# Iterating Over Dictionaries
d = {'a': 1, 'b': 2}

# Iterate keys
for key in d:
    print(key)

# Iterate values
for value in d.values():
    print(value)

# Iterate items (key, value)
for key, value in d.items():
    print(key, value)


a
b
1
2
a 1
b 2


In [125]:
# Dictionary Comprehension
# Square numbers 0-4 as dict
squares = {x: x**2 for x in range(5)}  # {0:0, 1:1, 2:4, 3:9, 4:16}

# Conditional comprehension
even_squares = {x: x**2 for x in range(5) if x % 2 == 0}  # {0:0, 2:4, 4:16}


In [126]:
import copy
d2 = copy.deepcopy(d)


In [128]:
# Checking Membership
d = {'a': 1, 'b': 2}

print('a' in d)   # True
print('c' not in d) # True


True
True


In [129]:
# Sorting Dictionaries

# By key:

d = {'b':2, 'a':1, 'c':3}
for k in sorted(d):
    print(k, d[k])


# By value:

for k, v in sorted(d.items(), key=lambda item: item[1]):
    print(k, v)


a 1
b 2
c 3
a 1
b 2
c 3


In [130]:
# Merging Dictionaries

# Python 3.9+:

d1 = {'a':1}
d2 = {'b':2}
d3 = d1 | d2  # {'a':1, 'b':2}


# Python <3.9:

d1.update(d2)


In [131]:
# Special Dictionary Types (Advanced, Sometimes Asked)

# defaultdict (from collections) → avoids KeyError:

from collections import defaultdict
d = defaultdict(int)
d['a'] += 1  # default 0


# OrderedDict (Python <3.7 → maintains order):

from collections import OrderedDict
od = OrderedDict()
od['a'] = 1
od['b'] = 2


# Counter → counts elements:

from collections import Counter
c = Counter(['a','b','a'])
print(c)  # Counter({'a':2,'b':1})


Counter({'a': 2, 'b': 1})


In [133]:
# Sorting a Dictionary

# You cannot sort a dict in place (until Python 3.7+, order is preserved), but you can get sorted lists of items or create a new sorted dictionary.

# a) Sort by Key
d = {'b': 2, 'a': 3, 'c': 1}

# Ascending by key
d_sorted_asc = dict(sorted(d.items()))
print(d_sorted_asc)  # {'a': 3, 'b': 2, 'c': 1}

# Descending by key
d_sorted_desc = dict(sorted(d.items(), reverse=True))
print(d_sorted_desc)  # {'c': 1, 'b': 2, 'a': 3}

# b) Sort by Value
d = {'b': 2, 'a': 3, 'c': 1}

# Ascending by value
d_val_asc = dict(sorted(d.items(), key=lambda item: item[1]))
print(d_val_asc)  # {'c': 1, 'b': 2, 'a': 3}

# Descending by value
d_val_desc = dict(sorted(d.items(), key=lambda item: item[1], reverse=True))
print(d_val_desc)  # {'a': 3, 'b': 2, 'c': 1}


{'a': 3, 'b': 2, 'c': 1}
{'c': 1, 'b': 2, 'a': 3}
{'c': 1, 'b': 2, 'a': 3}
{'a': 3, 'b': 2, 'c': 1}


#### Tuple

A tuple is an ordered, immutable collection of items, which can contain elements of different data types.

Tuples use less memory than lists; often used for immutable records.

Single element tuple must have a comma.

Tuples are immutable, but lists inside tuples are mutable.

t = (1,2,3) * 2 → (1,2,3,1,2,3)

t[1:3] → returns a tuple, not list.

Tuples can be dictionary keys (immutable).

No tuple comprehension: (x for x in range(5)) is generator.

Tuple comparison is lexicographical.

tuple() can convert iterables to tuples.

Only count() and index() are valid tuple methods

In [139]:
t1 = (1, 2, 3)
t = 1, 2, 3

t2 = ("apple", "banana", "cherry")
t3 = (1, "apple", 3.14)
empty = ()

# Single-element tuple:
# Tricky: A single element requires a comma ,

single = (5,)   # tuple
not_tuple = (5) # int


In [166]:
t = (23, 45, 67, 23, 89, 45, 78)
t.index(45, 5)

tuple([2])

(2,)

In [141]:
# Accessing Tuple Elements

# Indexing:

t = (10, 20, 30)
print(t[0])   # 10
print(t[-1])  # 30


# Slicing:

t = (0,1,2,3,4,5)
print(t[1:4])   # (1,2,3)
print(t[:3])    # (0,1,2)
print(t[3:])    # (3,4,5)
print(t[::-1])  # reversed tuple


10
30
(1, 2, 3)
(0, 1, 2)
(3, 4, 5)
(5, 4, 3, 2, 1, 0)


In [142]:
# Tuple Functions / Methods

# Tuples have very few methods because they are immutable. Important ones:

# count(x) → Returns how many times x appears

t = (1,2,2,3)
print(t.count(2))  # 2


# index(x) → Returns first index of x

t = (10, 20, 30)
print(t.index(20))  # 1


# Note: Tuples do not have append, remove, pop, extend, or sort methods (immutable).

2
1


In [143]:
# Tuple Packing & Unpacking

# Packing: Assign multiple values to a tuple

t = 1, 2, 3   # packed tuple


# Unpacking: Assign tuple elements to variables

a, b, c = t
print(a, b, c)  # 1 2 3


# Extended unpacking (Python 3+):

t = (1,2,3,4,5)
a, *b, c = t
print(a, b, c)  # 1 [2,3,4

1 2 3
1 [2, 3, 4] 5


In [138]:
t

(1, 2, 3)

#### Set

A set is an unordered, mutable collection of unique elements.

Defined using {} or set()

In [144]:
a = {1, 2, 3}
b = set([1, 2, 3])
c = set("hello")   # {'h','e','l','o'}


In [146]:
# Allowed (Immutable / Hashable)

# int, float, string

# tuple (only if it contains immutable items)

{1, "a", (2, 3)}

# Not Allowed: - list, dict, set

# Why lists are not allowed in sets?
# Because lists are mutable and unhashable

{(2, 3), 1, 'a'}

In [152]:
s = {10, 20, 30,2 }
# No indexing → s[0] 
# No slicing 
# Order not guaranteed
# Fast membership testing (in)

# add() → single element
s.add(5)

# update() → multiple elements
s.update([6, 7, 8])

In [153]:
# . Removing Elements (VERY IMPORTANT)
# Method	Error if not found
# remove()	❌ Yes
# discard()	✅ No
# pop()	Removes random element
# clear()	Empties set
s.remove(2)
s.discard(10)
x = s.pop()
s.clear()


# ⚠️ Exam trap:
# pop() does not remove first element (sets are unordered)

In [157]:
# Set Operations (HIGHEST WEIGHTAGE)

# Assume:

A = {1, 2, 3}
B = {3, 4, 5}

# Union
# A | B
A.union(B)

# Intersection
# A & B
A.intersection(B)

# Difference
# A - B
A.difference(B)

# Symmetric Difference
# A ^ B
# A.symmetric_difference(B)


{1, 2}

In [159]:
A = {1, 2}
B = {1, 2, 3}
# Method	Meaning
# A.issubset(B)	A ⊆ B
# A <= B	subset
# A < B	proper subset
# B.issuperset(A)	B ⊇ A
# A.isdisjoint(B)	no common elements

# 🔹 9. Frozen Sets (IMPORTANT THEORY)
# Immutable version of set

# Can be used as dictionary keys
fs = frozenset([1, 2, 3])
# ⚠️ You cannot add or remove elements from frozenset

# 🔹 10. Copying Sets
s2 = s.copy()

In [160]:
# Set Comprehension (IMPORTANT)
# s = {x*x for x in range(5)}


# With condition:

# s = {x for x in range(10) if x % 2 == 0}

# 🔹 13. Built-in Functions with Sets
# len(s)
# max(s)
# min(s)
# sum(s)
# sorted(s)   # returns list

# 🔹 14. Common Exam Output Questions
# s = {1, 2, 3}
# s.add(2)
# print(s)


# ✔ Output: {1, 2, 3}

# s = set("banana")
# print(len(s))


# ✔ Output: 3 ({'b','a','n'})

# 🔹 15. Time Complexity (THEORY QUESTION)
# Operation	Avg Time
# add	O(1)
# remove	O(1)
# search (in)	O(1)
# union/intersection	O(n)
# 🔹 16. Difference Between Set & List (VERY IMPORTANT)
# Feature	List	Set
# Ordered	Yes	No
# Duplicates	Yes	No
# Indexing	Yes	No
# Speed	Slower	Faster
# Mutable	Yes	Yes
# 🔹 17. Common Mistakes (EXAM TRAPS ⚠️)

# {} is dict, not set

# Sets don’t support indexing

# pop() removes random element

# Duplicate values removed

# Mutable elements not allowed

# 🔹 18. When to Use Sets (THEORY)

# Remove duplicates

# Membership testing

# Mathematical operations

# Fast lookup

# 🔹 19. One-Page Revision Summary 📝

# {} ≠ empty set

# Unique + unordered

# add() vs update()

# remove() vs discard()

# | & - ^

# frozenset is immutable

# No indexing/slicing

# If you want, next I can:

# 🔥 Give 50 MCQs with answers

# 🧠 Give previous-year exam questions

# 📝 Give only output-based tricky questions

# 🚀 Give 1-hour revision plan

#### Numpy

In [39]:
np.version
arr = np.array([0, 1, 2, 3, 4, 5, 56], dtype='float16')
print(arr)
arr[1:4]
np.ones((3, 5))

[ 0.  1.  2.  3.  4.  5. 56.]


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [57]:
print("Zeros: \n", np.zeros((3, 4)) )   # 3 rows, 4 columns
print("Idemntity: \n ", np.eye(4))
print("daigonal: \n", np.diag([1, 2, 3, 4]))
print("random int: \n", np.random.randint(0, 100, (3, 3)))
print("random: \n", np.random.rand(3, 3))
print("reshaping: \n", np.arange(1, 10).reshape(3, 3))
print("constant value: \n", np.full((2, 3), 7))


Zeros: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Idemntity: 
  [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
daigonal: 
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
random int: 
 [[36 63 71]
 [67 73  0]
 [40 72 55]]
random: 
 [[0.7195575  0.01800843 0.41057703]
 [0.69028957 0.50276974 0.17031773]
 [0.93880819 0.95827601 0.94452989]]
reshaping: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
constant value: 
 [[7 7 7]
 [7 7 7]]


In [58]:
# Upper & Lower triangular matrices
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

upper = np.triu(A)
lower = np.tril(A)

print("Upper:\n", upper)
print("Lower:\n", lower)

# Sparse-like matrix
S = np.zeros((4, 4))
S[1, 2] = 5
S[3, 0] = 9
print(S)

Upper:
 [[1 2 3]
 [0 5 6]
 [0 0 9]]
Lower:
 [[1 0 0]
 [4 5 0]
 [7 8 9]]
[[0. 0. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 0.]
 [9. 0. 0. 0.]]


#### Others